[package]
name = "freegsnke"
version = "3.1.0"
edition = "2021"

[lib]
name = "_freegsnke_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
rayon = "1.10"
faer = "0.24.4"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
