#!/usr/bin/env python3
"""
Generate a synthetic dataset of static equilibria for training and evaluating
surrogate initialisation models on MAST-U.

Samples are generated by perturbing and interpolating between validated
diverted and limited reference configurations with the ConstrainPaxisIp profile.
"""

import argparse
import os
import pickle
import time
from pathlib import Path

import numpy as np

from freegsnke import GSstaticsolver, build_machine, equilibrium_update
from freegsnke.jtor_update import ConstrainPaxisIp

ACTIVE_COIL_NAMES = [
    "Solenoid",
    "PX",
    "D1",
    "D2",
    "D3",
    "Dp",
    "D5",
    "D6",
    "D7",
    "P4",
    "P5",
    "P6",
]

FEATURE_NAMES = ACTIVE_COIL_NAMES + [
    "Ip",
    "paxis",
    "fvac",
    "alpha_m",
    "alpha_n",
]


def load_machine_and_baselines(repo_root: Path):
    """Load the MAST-U tokamak description and reference coil currents."""
    config_dir = repo_root / "machine_configs" / "MAST-U"
    tokamak = build_machine.tokamak(
        active_coils_path=str(config_dir / "MAST-U_like_active_coils.pickle"),
        passive_coils_path=str(config_dir / "MAST-U_like_passive_coils.pickle"),
        limiter_path=str(config_dir / "MAST-U_like_limiter.pickle"),
        wall_path=str(config_dir / "MAST-U_like_wall.pickle"),
    )

    data_dir = repo_root / "examples" / "data"
    with open(data_dir / "simple_diverted_currents_PaxisIp.pk", "rb") as f:
        div_currents = pickle.load(f)
    with open(data_dir / "simple_limited_currents_PaxisIp.pk", "rb") as f:
        lim_currents = pickle.load(f)

    return tokamak, div_currents, lim_currents


def sample_parameters(rng: np.random.Generator, div_currents: dict, lim_currents: dict):
    """
    Sample physical coil currents and profile parameters.
    Blends between diverted and limited reference states and applies perturbations.
    """
    mode = rng.choice(["diverted", "limited", "interpolated"], p=[0.45, 0.45, 0.10])
    weight = 1.0
    if mode == "diverted":
        base = {k: float(div_currents[k]) for k in ACTIVE_COIL_NAMES}
    elif mode == "limited":
        base = {k: float(lim_currents[k]) for k in ACTIVE_COIL_NAMES}
        weight = 0.0
    else:
        weight = rng.uniform(0.2, 0.8)
        base = {
            k: weight * float(div_currents[k]) + (1.0 - weight) * float(lim_currents[k])
            for k in ACTIVE_COIL_NAMES
        }

    currents = {}
    for k in ACTIVE_COIL_NAMES:
        nominal = base[k]
        if abs(nominal) < 50.0:
            # Near zero: small additive jitter
            perturbation = rng.uniform(-100.0, 100.0)
            currents[k] = nominal + perturbation
        else:
            # Multiplicative perturbation: +/- 10% to 25%
            fraction = rng.uniform(-0.20, 0.20)
            currents[k] = nominal * (1.0 + fraction)

    # Sample profile parameters consistent with magnetic configuration
    if mode == "diverted":
        Ip = rng.uniform(5.4e5, 6.8e5)
        paxis = rng.uniform(7.2e3, 9.0e3)
    elif mode == "limited":
        Ip = rng.uniform(3.5e5, 4.5e5)
        paxis = rng.uniform(5.0e3, 7.0e3)
    else:
        nom_Ip = weight * 6.2e5 + (1.0 - weight) * 4.0e5
        nom_paxis = weight * 8.1e3 + (1.0 - weight) * 6.0e3
        Ip = nom_Ip * (1.0 + rng.uniform(-0.10, 0.10))
        paxis = nom_paxis * (1.0 + rng.uniform(-0.10, 0.10))

    fvac = rng.uniform(0.42, 0.58)
    alpha_m = rng.uniform(1.5, 2.1)
    alpha_n = rng.uniform(1.0, 1.4)

    return mode, weight, currents, Ip, paxis, fvac, alpha_m, alpha_n


def generate_dataset(
    target_count: int = 250,
    seed: int = 42,
    output_path: str = "data/surrogate_dataset_mastu.npz",
    max_attempts: int = 500,
    target_tolerance: float = 1e-5,
):
    """Run forward static solves to generate a dataset of converged equilibria."""
    repo_root = Path(__file__).resolve().parents[1]
    tokamak, div_currents, lim_currents = load_machine_and_baselines(repo_root)

    rng = np.random.default_rng(seed)

    # Base equilibrium domain
    base_eq = equilibrium_update.Equilibrium(
        tokamak=tokamak,
        Rmin=0.1,
        Rmax=2.0,
        Zmin=-2.2,
        Zmax=2.2,
        nx=65,
        ny=129,
    )
    base_eq.tokamak_psi = base_eq.tokamak.getPsitokamak(vgreen=base_eq._vgreen)

    # Instantiate the nonlinear solver once
    solver = GSstaticsolver.NKGSsolver(base_eq, gs_operator_order=4)

    # Pre-solve nominal reference equilibria to provide robust initial guesses
    print("Solving reference diverted equilibrium...", flush=True)
    div_eq = base_eq.create_auxiliary_equilibrium()
    for k in ACTIVE_COIL_NAMES:
        div_eq.tokamak.set_coil_current(k, div_currents[k])
    div_prof = ConstrainPaxisIp(eq=div_eq, paxis=8.1e3, Ip=6.2e5, fvac=0.5, alpha_m=1.8, alpha_n=1.2)
    solver.forward_solve(div_eq, div_prof, target_relative_tolerance=1e-5, max_solving_iterations=60, suppress=True)
    div_ref_psi = np.copy(div_eq.plasma_psi)

    print("Solving reference limited equilibrium...", flush=True)
    lim_eq = base_eq.create_auxiliary_equilibrium()
    for k in ACTIVE_COIL_NAMES:
        lim_eq.tokamak.set_coil_current(k, lim_currents[k])
    lim_prof = ConstrainPaxisIp(eq=lim_eq, paxis=6.0e3, Ip=4.0e5, fvac=0.5, alpha_m=1.8, alpha_n=1.2)
    solver.forward_solve(lim_eq, lim_prof, target_relative_tolerance=1e-5, max_solving_iterations=60, suppress=True)
    lim_ref_psi = np.copy(lim_eq.plasma_psi)

    X_list = []
    Y_list = []
    metadata = []

    print(f"Starting dataset generation: target={target_count} equilibria, seed={seed}", flush=True)
    start_time = time.time()
    attempts = 0

    while len(X_list) < target_count and attempts < max_attempts:
        attempts += 1
        mode, weight, currents, Ip, paxis, fvac, alpha_m, alpha_n = sample_parameters(
            rng, div_currents, lim_currents
        )

        # Auxiliary equilibrium instance avoids reloading machine description
        eq = base_eq.create_auxiliary_equilibrium()
        if mode == "diverted":
            eq.plasma_psi = np.copy(div_ref_psi)
        elif mode == "limited":
            eq.plasma_psi = np.copy(lim_ref_psi)
        else:
            eq.plasma_psi = weight * div_ref_psi + (1.0 - weight) * lim_ref_psi
        eq.solved = False

        for k in ACTIVE_COIL_NAMES:
            eq.tokamak.set_coil_current(k, currents[k])

        try:
            profiles = ConstrainPaxisIp(
                eq=eq,
                paxis=paxis,
                Ip=Ip,
                fvac=fvac,
                alpha_m=alpha_m,
                alpha_n=alpha_n,
            )
        except Exception:
            continue

        t0 = time.time()
        try:
            solver.forward_solve(
                eq,
                profiles,
                target_relative_tolerance=target_tolerance,
                max_solving_iterations=30,
                suppress=True,
            )
            solve_time = time.time() - t0

            if eq.solved and solver.relative_change <= max(target_tolerance, 1e-4):
                feature_vec = [currents[k] for k in ACTIVE_COIL_NAMES] + [
                    Ip,
                    paxis,
                    fvac,
                    alpha_m,
                    alpha_n,
                ]
                X_list.append(feature_vec)
                Y_list.append(eq.plasma_psi.copy())
                metadata.append(
                    {
                        "mode": mode,
                        "iterations": solver.norm_rel_change,
                        "rel_change": solver.relative_change,
                        "solve_time": solve_time,
                    }
                )

                if len(X_list) % 25 == 0:
                    elapsed = time.time() - start_time
                    rate = len(X_list) / elapsed
                    print(
                        f"Progress: {len(X_list)}/{target_count} converged "
                        f"({attempts} attempts, rate={rate:.2f} solves/s)",
                        flush=True,
                    )
        except Exception:
            continue

    total_time = time.time() - start_time
    print(
        f"Completed: {len(X_list)}/{target_count} equilibria generated in "
        f"{total_time:.1f}s ({attempts} attempts)."
    )

    if len(X_list) < target_count:
        print(f"Warning: Only reached {len(X_list)}/{target_count} samples.")

    X = np.array(X_list, dtype=np.float64)
    Y = np.array(Y_list, dtype=np.float64)

    # Train/test split (80% train, 20% test)
    n_samples = len(X)
    n_train = int(n_samples * 0.8)
    indices = rng.permutation(n_samples)
    train_idx = indices[:n_train]
    test_idx = indices[n_train:]

    out_file = repo_root / output_path
    out_file.parent.mkdir(parents=True, exist_ok=True)

    np.savez_compressed(
        out_file,
        X=X,
        Y=Y,
        train_idx=train_idx,
        test_idx=test_idx,
        feature_names=FEATURE_NAMES,
        R_1D=base_eq.R_1D,
        Z_1D=base_eq.Z_1D,
    )
    print(f"Saved dataset to {out_file} (file size: {out_file.stat().st_size / 1024:.1f} KB)")
    return out_file


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate surrogate training dataset")
    parser.add_argument("--count", type=int, default=250, help="Number of converged equilibria to generate")
    parser.add_argument("--seed", type=int, default=42, help="Random number generator seed")
    parser.add_argument("--output", type=str, default="data/surrogate_dataset_mastu.npz", help="Output file path")
    args = parser.parse_args()

    generate_dataset(target_count=args.count, seed=args.seed, output_path=args.output)
